#! /bin/sh

# WPG Colors / Wallpaper
xrdb -merge /home/sky/.Xresources
background=$(xrdb -query | grep "background" | cut -f2 | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | head -n 1)
color9=$(xrdb -query | grep "color9" | cut -f2 | head -n 1)
${HOME}/.config/wpg/wp_init.sh
$HOME/.config/polybar/launch.sh
nitrogen --restore &

# Base BSPWM 
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9 10
bspc config border_width         3
bspc config window_gap          15
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         0
bspc config right_padding        0
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a gimp desktop='^5' state=floating follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a Evolution desktop='^3' state=tiling
bspc rule -a spotify state=floating
bspc rule -a firefox desktop='^1' focus=on
bspc rule -a Screenkey manage=on
bspc rule -a ImageMagick state=floating rectangle=631x470+185+188
bspc rule -a Display state=floating rectangle=631x470+185+188 

bspc config normal_border_color $color0
bspc config active_border_color $color1
bspc config focused_border_color $color5
bspc config presel_feedback_color $color1

# ---- What to run

xsetroot -cursor_name left_ptr &
numlockx & 
mpd &
picom --experimental-backends --blur-method dual_kawase --blur-strength 5 &
dunst &
    
