#! /bin/sh

# Base BspWM stuff
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9 10
bspc config border_width         3
bspc config window_gap          15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding          20
bspc config bottom_padding       20
bspc config left_padding         0
bspc config right_padding        0
bspc config focus_follows_pointer true
bspc rule -a gimp desktop='^5' state=floating follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a evolution desktop='^3' follow=on 
bspc rule -a spotify state=floating
bspc rule -a firefox desktop='^1' focus=on
bspc rule -a Screenkey manage=on
bspc config normal_border_color "#58427b"
bspc config focused_border_color "#2a64ab"
bspc config active_border_color "#5e81ac"

# ---- What to run

xsetroot -cursor_name left_ptr &
numlockx & 
nitrogen --restore
picom -bc --config ~/.config/picom/picom.conf &
mpd &
dunst &

# Polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -cr ~/.config/polybar/topbar.ini main --reload &
    MONITOR=$m polybar -cr ~/.config/polybar/bottombar.ini main --reload &
  done
else
  polybar --reload example &
fi

